### ISSUE TITLE
Crashed with iris shader

### ISSUE THREAD

**Issue by leon7104** [matthewperiut/Chisel-Fabric#1]
[crash-2021-12-18_21.31.54-client.txt](https://github.com/matthewperiut/Chisel-Fabric/files/7739301/crash-2021-12-18_21.31.54-client.txt)

**Comment by matthewperiut** [comment]
I am unable to replicate, Iris + Indium + Sodium + Chisel works under 1.17 and 1.18 work, therefore I am closing the issue. Update this issue if you're able to find the true culprit.
