### ISSUE TITLE
crashes on 1.18.2

### ISSUE THREAD

**Issue by Redd56** [matthewperiut/Chisel-Fabric#11]
[here](https://pastebin.com/RxY9xAq0) is the initial crashlog, i wish you the best on your 1.18.2 update. that is all have a wonderful week.

**Comment by matthewperiut** [comment]
Thanks for letting me know! I fixed it recently in version 1.4.5, and it's now on CurseForge
Have a wonderful week to you too!

**Comment by Redd56** [comment]
Will as well
