### ISSUE TITLE
Activating chisel menu should not also trigger off-hand action

### ISSUE THREAD

**Issue by Flashfyre** [matthewperiut/Chisel-Fabric#12]
When I'm holding a torch or block in my off-hand and I activate the chisel menu, it also places the off-hand item since there seems to be no cancellation of the off-hand action upon opening the menu. Ideally, activating the chisel menu would count as a main hand action that overrides the off-hand action. I am playing on 1.18.1 with version 1.4.4.

**Comment by matthewperiut** [comment]
Fixed in 1.19's 1.4.6
