### ISSUE TITLE
Blockpacks no longer get loaded on 1.3.X

### ISSUE THREAD

**Issue by Ratismal** [matthewperiut/Chisel-Fabric#3]
It seems that blockpack functionality was completely removed in version 1.3.X. Is this intentional, and the way that this mod will be moving forwards in the future? Because if so, I don't think there's really any reason to use it.

**Comment by Ratismal** [comment]
Discussed in discord, response was
> I'll reimplement the AARP data-driven parts of the mod in 1.4.x, that's why I'm still holding two branches on github, but right now I'm going about a precompiled data driven approach with python scripts for better load times for the large mass of the blocks, because I added 1000 more blocks on top of the already 1,200 that were already there and my crappy laptop was at it's knees at load times. sorry for giving you a bad time, I should of made it more obvious on the page where it says that 1.3 and 1.2 aren't compatible, but when I drop 1.4.x all the previous blocks should be able to load
So I'll close this issue for now!

**Comment by matthewperiut** [comment]
This is fixed completely in 1.4.1, with automatically replacing blocks that were in 1.2 to the 1.3 version.
