### ISSUE TITLE
Crash 1.18.1 (Exit Code -1)

### ISSUE THREAD

**Issue by PeacefulChaos94** [matthewperiut/Chisel-Fabric#5]
[crash-2021-12-19_13.59.50-client.txt](https://github.com/matthewperiut/Chisel-Fabric/files/7741677/crash-2021-12-19_13.59.50-client.txt)

**Comment by PixusPanic** [comment]
I'm having the same issue, albeit with a different set of mods.

**Comment by matthewperiut** [comment]
1.4.1 resolves the issue, which is not having AARP included by default
