### ISSUE TITLE
(Chisel[1.4.2]) is incompatible with Java version 18(18-ea)

### ISSUE THREAD

**Issue by EndlessEden** [matthewperiut/Chisel-Fabric#7]
Chisel throws errors with versions of java newer than 17. While 17 is required, it will eventually be replaced with 18.

All of my testing environments use Oracle JDK 18-ea, thus i cannot use this mod or any modpack containing it

**Comment by matthewperiut** [comment]
I have made Chisel 1.4.4 (1.18) work with java 17 and 18
