### ISSUE TITLE
Chisel menu not opening

### ISSUE THREAD

**Issue by WagnerCaetano** [matthewperiut/Chisel-Fabric#8]
Hello..

I'm currently playing the modpack Another Quality Modpack 2 version 1.4.1 on Minecraft 1.18.1 and when i right click the chisel tool for open the inventory with the options of block variations nothing happens..

i dont know if u need more information about the bug, but i'l try to help anyway..

**Comment by matthewperiut** [comment]
I know all about the bug, update to the latest version of Another Quality Modpack 2 and it will be resolved alternatively download the latest version of the chisel and install that, and it will be resolved.
